name: Deploy to Github Pages
on:
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: 'latest'
          extended: true
      - name: Update Hugo Modules
        run: hugo mod tidy
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install node modules
        run: |
          hugo mod npm pack
          npm install        
      - name: Build
        run: hugo --cleanDestinationDir --minify
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.0
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_branch: main
          publish_dir: ./public